coverage:
    status:
        project:
            default:
                paths:
                    - "src"
                target: 80
                threshold: 80%
                base: auto

comment:
    behavior: default
    require_changes: false
    require_base: false
    require_head: true
    hide_project_coverage: false
