#!/bin/sh

set -Ux LLVM_BUILD "/opt/llvm-21"

set -Ux LD_LIBRARY_PATH "$LLVM_BUILD/lib:$LD_LIBRARY_PATH"
set -Ux PATH "$LLVM_BUILD/bin:$PATH"

set -Ux LLVM_SYS_211_PREFIX "$LLVM_BUILD"
set -Ux MLIR_SYS_210_PREFIX "$LLVM_BUILD"
set -Ux TABLEGEN_210_PREFIX "$LLVM_BUILD"

