name: 'Install LLVM Dependencies'
description: 'Install LLVM and related dependencies'
runs:
  using: "composite"
  steps:
    - name: Add LLVM Debian repository
      uses: myci-actions/add-deb-repo@11
      with:
        repo: deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main
        repo-name: llvm-repo
        keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key

    - name: Update and upgrade APT
      shell: bash
      run: sudo apt-get update && sudo apt-get upgrade -y

    - name: Install LLVM
      shell: bash
      run: sudo apt-get install llvm-22 llvm-22-dev llvm-22-runtime clang-22 clang-tools-22 lld-22 libpolly-22-dev libmlir-22-dev mlir-22-tools
