name: Release on crates.io

permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-24.04
    env:
        MLIR_SYS_220_PREFIX: /usr/lib/llvm-22/
        LLVM_SYS_221_PREFIX: /usr/lib/llvm-22/
        TABLEGEN_220_PREFIX: /usr/lib/llvm-22/
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust env
        uses: dtolnay/rust-toolchain@1.94.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install LLVM Dependencies
        uses: ./.github/actions/install-llvm-deps
      
      - name: Install GiNaC
        shell: bash
        run: sudo apt install libginac-dev
         

      - name: Publish Mathic
        run: |
          cargo login ${CRATES_TOKEN}
          cargo publish --all-features
